### ISSUE TITLE
Make it compatible with  http: ^0.13.1

### ISSUE THREAD

**Issue by AryashDubey** [madhavtripathi05/insta_public_api#1]
Because insta_public_api >=0.1.1 depends on http 0.13.0 and wml_web_project depends on http ^0.13.1, insta_public_api >=0.1.1 is forbidden.
This is the error I am receiving.

**Comment by madhavtripathi05** [comment]
Thanks I'll do it the next update, but for now just add this after your dependencies:

dependency_overrides:
  http: ^0.13.1

**Comment by madhavtripathi05** [comment]
Updated in v0.1.2
