### ISSUE TITLE
Api Error

### ISSUE THREAD

**Issue by TicketMarketTecnologia** [madhavtripathi05/insta_public_api#2]
HTML was returned instead of JSON
      i.e.You might have surpassed Instagram's no. of requests/hour limit

**Comment by madhavtripathi05** [comment]
well, it's a pretty clear message that you have surpassed the limit. wait for few hours and everything should work as expected.

**Comment by TicketMarketTecnologia** [comment]
In fact, in the first consultation this is already happening, the return rarely works.

Unfortunately, if an API takes into account the simultaneous access of different applications that use the same endpoint, they should always show an error.

It ends up being useless to use it in a production application.

**Comment by madhavtripathi05** [comment]
Totally agreed, this is not a production ready solution. You may checkout [Instagram's official API](https://developers.facebook.com/docs/instagram-basic-display-api) if you're planning to deploy this on large scale.

**What does this package do?**
I'm just fetching data from this endpoint: https://www.instagram.com/your_username/?__a=1 which totally works for a few times in a row but will not, if you try to call it again and again and there is nothing much I can do about that. for more info check [this](https://medium.com/@vasu.pal/crawl-instagram-profiles-and-posts-the-most-efficient-way-possible-without-fb-graph-api-7ea270b11e74) article.
